[package]
name = "saildb_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
saildb = { path = "../saildb" }
structopt = "0.3"
sia = "0.0.4"

[[bin]]
name = "server"

[[bin]]
name = "client"
